
FROM python:3.11-slim


RUN mkdir /app
 

WORKDIR /app

ENV PORT 8000  
 

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1 
 

RUN pip install --upgrade pip 
 

COPY requirements.txt  /app/
 

RUN pip install --no-cache-dir -r requirements.txt
 

COPY . /app/
 

CMD gunicorn fileShareBackend.wsgi:application --bind 0.0.0.0:"${PORT}"


EXPOSE ${PORT}
