# Generated by Django 5.1.5 on 2025-02-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_encryptedfile_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='salt',
            field=models.CharField(default='', max_length=64),
        ),
    ]
