# Generated by Django 5.1.5 on 2025-02-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_encryptedfile_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='public_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='public_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
